import type { Metadata } from "next";
import localFont from "next/font/local";
import StoreProvider from "./__lib/StoreProvider";

import "./globals.css";
import { ReactReduxContext } from "react-redux";

const nbInternational = localFont({
  src: "../public/fonts/nb-regular.otf",
  variable: "--font-nb",
});

export const metadata: Metadata = {
  title: "Superpower | Unlock your new health intelligence | Biomarker Testing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
