// app/layout.tsx
import type { Metadata } from "next";
import StoreProvider from "./__lib/StoreProvider";
import StoreInitializer from "./__lib/StoreInitializer"; 
import "./globals.css";

export const metadata: Metadata = {
  title: "Superpower | Unlock your new health intelligence | Biomarker Testing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <StoreInitializer />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}